[tool.poetry]
name = "portfolio-tracker"
version = "0.1.0"
description = "Un'applicazione web con Streamlit per l'analisi approfondita di ETF e portafogli di investimento."
authors = ["francescoiga7 francescoiga7@gmail.com"]
readme = "README.md"
packages = [
    { include = "etf_metrics" }
]

[tool.poetry.dependencies]
python = ">=3.9, <4.0"
streamlit = "*"
pandas = "*"
numpy = "*"
plotly = "*"
yfinance = "*"
requests = "*"
beautifulsoup4 = "*"
matplotlib = "*"
scipy = "*"
pyarrow = "*"

[tool.poetry.group.dev.dependencies]
poe-the-poet = "*"
black = "*"
pytest = "*"

[tool.poe.tasks]
start = "streamlit run app.py"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"