[project]
name = "portfolio-tracker"
version = "0.1.0"
description = "Un'applicazione web con Streamlit per l'analisi approfondita di ETF e portafogli di investimento."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "streamlit",
    "pandas",
    "numpy",
    "plotly",
    "yfinance",
    "requests",
    "polars",
]

[dependency-groups]
dev = [
    "black",
    "pytest",
    "pandas-stubs",
]
